apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
    mapUsers: |
      - userarn: arn:aws:iam::851725526893:user/github-ci
        username: github-ci
        groups:
          - system:masters

    mapRoles: |
      - groups:
        - system:bootstrappers
        - system:nodes
        rolearn: arn:aws:iam::851725526893:role/GithubAction
        username: system:node:{{EC2PrivateDNSName}}